# Generated by Django 4.0.4 on 2022-06-22 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_short_url_active_alter_short_url_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='short_url',
            name='long_url',
            field=models.TextField(unique=True),
        ),
    ]
