# Generated by Django 4.0.4 on 2022-06-22 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_alter_short_url_long_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='short_url',
            name='short_url',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
