# Generated by Django 4.0.4 on 2022-06-25 07:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('account', '0006_alter_short_url_short_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='shortner_urls',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_url', models.CharField(max_length=200, unique=True)),
                ('long_url', models.URLField(null=True, verbose_name='URL')),
                ('qr_code', models.ImageField(blank=True, upload_to='qe_code')),
                ('link_date', models.DateField(auto_now_add=True)),
                ('active', models.BooleanField(default=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
