# Generated by Django 4.0.4 on 2022-06-25 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_shortner_urls'),
    ]

    operations = [
        migrations.DeleteModel(
            name='shortner_urls',
        ),
    ]
