# Generated by Django 4.0.4 on 2022-06-25 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='short_url2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_url', models.CharField(max_length=200, unique=True)),
                ('long_url', models.URLField(null=True, verbose_name='URL')),
                ('qr_code', models.ImageField(blank=True, upload_to='qe_code')),
                ('link_date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
